# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ink < Formula
  desc "Markdown previewer for a local library"
  homepage "https://github.com/econron/ink"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/econron/ink/releases/download/v0.1.1/ink_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "1642341e1226258cb89fdd3b28055d753c249c05123afd8dfa59eb21ffe7a966"

      define_method(:install) do
        bin.install "ink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/econron/ink/releases/download/v0.1.1/ink_0.1.1_Darwin_arm64.tar.gz"
      sha256 "84aab4308c9ec164e6fb9849f68ddf4cd5e3240f2290d41912da61d92f02176e"

      define_method(:install) do
        bin.install "ink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/econron/ink/releases/download/v0.1.1/ink_0.1.1_Linux_x86_64.tar.gz"
      sha256 "ec65ee70956c67001008f615167880a6c46cc23bb588b98342c1e1998f0e4fb9"
      define_method(:install) do
        bin.install "ink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/econron/ink/releases/download/v0.1.1/ink_0.1.1_Linux_arm64.tar.gz"
      sha256 "6ae0389558dc084340cfadcac2126ae2063bdd632433f62a0c2626bfb580e60c"
      define_method(:install) do
        bin.install "ink"
      end
    end
  end

  test do
    system "#{bin}/ink", "--help"
  end
end
