# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raku < Formula
  desc "GitHub PR review workflow helper"
  homepage "https://github.com/econron/raku"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/econron/raku/releases/download/v0.1.1/raku_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "ad9ee9ac2a73f09a8b4d8756e0ba8f63055cd650e4686029e6771e3146ac9e3f"

      define_method(:install) do
        bin.install "raku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/econron/raku/releases/download/v0.1.1/raku_0.1.1_Darwin_arm64.tar.gz"
      sha256 "03086b037db54d62ecbd1b8d7d3cc760d6eb29942b17d0a5316dadc27c2867de"

      define_method(:install) do
        bin.install "raku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/econron/raku/releases/download/v0.1.1/raku_0.1.1_Linux_x86_64.tar.gz"
      sha256 "d05e1475b2907d62d88e6ccb53d6431f44ea80a810948223266a66ff33e502e1"
      define_method(:install) do
        bin.install "raku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/econron/raku/releases/download/v0.1.1/raku_0.1.1_Linux_arm64.tar.gz"
      sha256 "bed7ec4fed145c144adde4f1cb4708d1543531d97a246dbfdf5e6431b4ff6cac"
      define_method(:install) do
        bin.install "raku"
      end
    end
  end

  test do
    system "#{bin}/raku", "--help"
  end
end
